var tableDonTamTru = [
    {
        "id": 1,
        "hoTen": "Phạm Văn Oanh",
        "gioiTinh": " Nữ",
        "ngaySinh": "01/06/1987",
        "SDT": "0470569940",
        "CCCD": "021110154128",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhiếp ảnh gia",
        "DDTamTru": "Xã Bắc Phú, Huyện Hoàn Kiếm, Thanh Hóa",
        "ngayBatDau": "13/01/2023",
        "ngayKetThuc": "19/02/2023",
        "lyDo": "Sửa chữa hoặc tu sửa nhà cần di dời tạm thời.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 2,
        "hoTen": "Hoàng Trọng Linh",
        "gioiTinh": " Nữ",
        "ngaySinh": "18/05/2005",
        "SDT": "0608044571",
        "CCCD": "050102041949",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhà báo",
        "DDTamTru": "Xã Hòa Minh, Huyện Đống Đa, Thanh Hóa",
        "ngayBatDau": "14/05/2023",
        "ngayKetThuc": "30/06/2023",
        "lyDo": "Sơ tán do thảm họa tự nhiên như lũ lụt hoặc bão.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 3,
        "hoTen": "Huỳnh Trọng Dũng",
        "gioiTinh": "Nam",
        "ngaySinh": "28/11/1983",
        "SDT": "0806778345",
        "CCCD": "087126948028",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Biên tập viên",
        "DDTamTru": "Xã Bắc Phú, Huyện Hai Châu, Hải Dương",
        "ngayBatDau": "14/10/2023",
        "ngayKetThuc": "09/11/2023",
        "lyDo": "Việc pháp lý hoặc xuất hiện tại tòa ở địa điểm khác.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 4,
        "hoTen": "Nguyễn Thị Oanh",
        "gioiTinh": "Nữ",
        "ngaySinh": "29/12/1989",
        "SDT": "0481003646",
        "CCCD": "026280925537",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Đạo diễn",
        "DDTamTru": "Xã Nam Sơn, Huyện Hai Bà Trưng, Nghệ An",
        "ngayBatDau": "15/05/2023",
        "ngayKetThuc": "09/06/2023",
        "lyDo": "Du lịch mùa lễ hội dài ngày.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 5,
        "hoTen": "Lê Minh Oanh ",
        "gioiTinh": "Nữ",
        "ngaySinh": "12/03/1989",
        "SDT": "0811934464",
        "CCCD": "052192330792",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Diễn viên",
        "DDTamTru": "Xã Đại Phú, Huyện Hai Bà Trưng, Đà Nẵng",
        "ngayBatDau": "16/05/2023",
        "ngayKetThuc": "27/06/2023",
        "lyDo": "Tham gia giải đấu thể thao hoặc sự kiện.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 6,
        "hoTen": "Vũ Thành Dũng",
        "gioiTinh": " Nữ",
        "ngaySinh": "04/01/2001",
        "SDT": "0642639347",
        "CCCD": "037154844018",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Ca sĩ",
        "DDTamTru": "Xã Hòa Minh, Huyện Cầu Giấy, Hải Dương",
        "ngayBatDau": "16/08/2023",
        "ngayKetThuc": "02/09/2023",
        "lyDo": "Tham gia vào hoạt động văn hóa hoặc nghệ thuật.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 7,
        "hoTen": "Huỳnh Tiến Dũng ",
        "gioiTinh": "Nam",
        "ngaySinh": "31/07/1980",
        "SDT": "0577983492",
        "CCCD": "019111925259",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhạc sĩ",
        "DDTamTru": "Xã Phú Lâm, Huyện Đống Đa, Hà Nội",
        "ngayBatDau": "17/02/2023",
        "ngayKetThuc": "21/03/2023",
        "lyDo": "Tham dự trại hè hoặc tu tập.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 8,
        "hoTen": "Phan Thành Bảo ",
        "gioiTinh": "Nữ",
        "ngaySinh": "16/01/1999",
        "SDT": "0226838566",
        "CCCD": "003269927756",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Họa sĩ",
        "DDTamTru": "Xã Phú Lâm, Huyện Ba Đình, TP Hồ Chí Minh",
        "ngayBatDau": "18/04/2023",
        "ngayKetThuc": "01/05/2023",
        "lyDo": "Tu dưỡng sức khỏe và tinh thần.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 9,
        "hoTen": "Phạm Hữu Cường",
        "gioiTinh": "Nam",
        "ngaySinh": "27/04/2000",
        "SDT": "0178894602",
        "CCCD": "052251541309",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhà thiết kế thời trang",
        "DDTamTru": "Xã Nam Sơn, Huyện Hai Bà Trưng, Thanh Hóa",
        "ngayBatDau": "18/06/2023",
        "ngayKetThuc": "23/06/2023",
        "lyDo": "Nghỉ phép cá nhân cho sự nghỉ ngơi và phục hồi.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 10,
        "hoTen": "Hoàng Minh Anh ",
        "gioiTinh": "Nữ",
        "ngaySinh": "24/03/1994",
        "SDT": "0545891806",
        "CCCD": "043124844588",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ may",
        "DDTamTru": "Xã Đại Phú, Huyện Hai Châu, Hải Phòng",
        "ngayBatDau": "19/03/2023",
        "ngayKetThuc": "28/03/2023",
        "lyDo": "Theo đuổi sở thích hoặc mục tiêu một cách chuyên sâu, như chuyến đi chụp ảnh.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 11,
        "hoTen": "Đặng Đức Quân",
        "gioiTinh": "Nam",
        "ngaySinh": "29/04/1998",
        "SDT": "0461086977",
        "CCCD": "084124008036",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ làm tóc",
        "DDTamTru": "Xã Đông Hải, Huyện Ba Đình, Đà Nẵng",
        "ngayBatDau": "19/07/2023",
        "ngayKetThuc": "16/08/2023",
        "lyDo": "Đào bới khảo cổ hoặc nghiên cứu lịch sử.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 12,
        "hoTen": "Trần Khắc Khoa",
        "gioiTinh": "Nam",
        "ngaySinh": "30/06/1991",
        "SDT": "0328478324",
        "CCCD": "026155607984",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Chuyên viên làm đẹp",
        "DDTamTru": "Xã Bắc Phú, Huyện Ba Đình, Hải Dương",
        "ngayBatDau": "20/01/2023",
        "ngayKetThuc": "14/02/2023",
        "lyDo": "Làm việc mùa vụ ở khu vực khác.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 13,
        "hoTen": "Võ Khắc Hiếu",
        "gioiTinh": "Nam",
        "ngaySinh": "05/03/1990",
        "SDT": "0331599332",
        "CCCD": "035121587765",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ sửa chữa điện tử",
        "DDTamTru": "Xã Đông Hải, Huyện Cầu Giấy, Thanh Hóa",
        "ngayBatDau": "21/01/2023",
        "ngayKetThuc": "24/02/2023",
        "lyDo": "Chuyến đi săn hoặc câu cá kéo dài.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 14,
        "hoTen": "Nguyễn Khắc Quân",
        "gioiTinh": "Nam",
        "ngaySinh": "10/11/1991",
        "SDT": "0541575475",
        "CCCD": "072106133064",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Kỹ thuật viên máy tính",
        "DDTamTru": "Xã Phú Lâm, Huyện Hai Châu, Hà Nội",
        "ngayBatDau": "21/04/2023",
        "ngayKetThuc": "23/05/2023",
        "lyDo": "Hoạt động chính trị hoặc vận động.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 15,
        "hoTen": "Trần Thành Dung",
        "gioiTinh": "Nữ",
        "ngaySinh": "07/09/1999",
        "SDT": "0375729582",
        "CCCD": "015128116457",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên tiếp thị",
        "DDTamTru": "Xã Thượng Đức, Huyện Đống Đa, Hải Dương",
        "ngayBatDau": "21/09/2023",
        "ngayKetThuc": "02/11/2023",
        "lyDo": "Tham gia chương trình cai nghiện hoặc phục hồi sức khỏe.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 16,
        "hoTen": "Phạm Văn Thu",
        "gioiTinh": "Nữ",
        "ngaySinh": "30/03/2005",
        "SDT": "0196597410",
        "CCCD": "046100310011",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Chuyên gia SEO",
        "DDTamTru": "Xã Trung Hưng, Huyện Hai Châu, Cần Thơ",
        "ngayBatDau": "21/10/2023",
        "ngayKetThuc": "26/11/2023",
        "lyDo": "Tham gia chương trình truyền hình thực tế hoặc cuộc thi.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 17,
        "hoTen": "Lê Ngọc Linh",
        "gioiTinh": "Nữ",
        "ngaySinh": "14/06/1994",
        "SDT": "0868263721",
        "CCCD": "089166265020",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhà phân tích dữ liệu",
        "DDTamTru": "Xã Đại Phú, Huyện Tây Hồ, Hải Phòng",
        "ngayBatDau": "22/04/2023",
        "ngayKetThuc": "03/06/2023",
        "lyDo": "Tham gia sự kiện từ thiện đường dài như marathon.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 18,
        "hoTen": "Phan Khắc Bảo",
        "gioiTinh": "Nam",
        "ngaySinh": "17/12/1983",
        "SDT": "0268119605",
        "CCCD": "047192614417",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Chuyên gia tư vấn",
        "DDTamTru": "Xã Đông Hải, Huyện Hoàn Kiếm, Thanh Hóa",
        "ngayBatDau": "22/05/2023",
        "ngayKetThuc": "11/07/2023",
        "lyDo": "Học và thi cử kéo dài.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 19,
        "hoTen": "Nguyễn Thị Linh",
        "gioiTinh": "Nữ",
        "ngaySinh": "20/10/1996",
        "SDT": "0897298434",
        "CCCD": "002220566062",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Luật sư",
        "DDTamTru": "Xã Thượng Đức, Huyện Cầu Giấy, Cần Thơ",
        "ngayBatDau": "24/05/2023",
        "ngayKetThuc": "11/07/2023",
        "lyDo": "Di dời tạm thời do bất ổn hoặc nguy hiểm trong khu vực.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 20,
        "hoTen": "Mai Quốc Bảo",
        "gioiTinh": "Nam",
        "ngaySinh": "03/12/1982",
        "SDT": "0621323256",
        "CCCD": "076148524080",
        "DDThuongTru": "An Thượng, Hà Nội",
        "ngheNghiep": "Giáo viên",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "21/04/2023",
        "ngayKetThuc": "28/05/2023",
        "lyDo": "Đi công tác dài hạn.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 21,
        "hoTen": "Huỳnh/Hoàng Chi Mai",
        "gioiTinh": "Nữ",
        "ngaySinh": "12/03/1990",
        "SDT": "0649088192",
        "CCCD": "029254100614",
        "DDThuongTru": "Đồng Tâm, Mỹ Đức, Hà Nội",
        "ngheNghiep": "Bác sĩ",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "05/10/2023",
        "ngayKetThuc": "13/11/2023",
        "lyDo": "Chuẩn bị cho triển lãm nghệ thuật.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 22,
        "hoTen": "Điền Nguyệt Cầm",
        "gioiTinh": "Nữ",
        "ngaySinh": "12/05/2002",
        "SDT": "0867132823",
        "CCCD": "078194261786",
        "DDThuongTru": "Hoàng Long, Phú Xuyên, Hà Nội",
        "ngheNghiep": "Y tá",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "27/08/2023",
        "ngayKetThuc": "27/09/2023",
        "lyDo": "Thăm người thân đang ốm.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 23,
        "hoTen": "Lê Thanh Hằng",
        "gioiTinh": "Nữ",
        "ngaySinh": "22/07/1980",
        "SDT": "0366180886",
        "CCCD": "028123989370",
        "DDThuongTru": "Khương Đình, Hà Nội",
        "ngheNghiep": "Kỹ sư",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "31/08/2023",
        "ngayKetThuc": "06/10/2023",
        "lyDo": "Thực tập chuyên nghiệp.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 24,
        "hoTen": "Ngô Ý Nhiên",
        "gioiTinh": "Nữ",
        "ngaySinh": "25/11/1999",
        "SDT": "0277561431",
        "CCCD": "026228633627",
        "DDThuongTru": "Lĩnh Nam, Hà Nội",
        "ngheNghiep": "Lập trình viên",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "07/02/2023",
        "ngayKetThuc": "07/03/2023",
        "lyDo": "Nghiên cứu khoa học.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 25,
        "hoTen": "Phan Công Vinh",
        "gioiTinh": "Nam",
        "ngaySinh": "14/12/1987",
        "SDT": "0782018972",
        "CCCD": "019225082942",
        "DDThuongTru": "Ngọc Hà, Hà Nội",
        "ngheNghiep": "Kiến trúc sư",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "24/11/2023",
        "ngayKetThuc": "16/12/2023",
        "lyDo": "Tham gia một dự án xây dựng.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 26,
        "hoTen": "Lý Ngọc Bích",
        "gioiTinh": "Nữ",
        "ngaySinh": "16/07/1984",
        "SDT": "0578983660",
        "CCCD": "031190982347",
        "DDThuongTru": "Ngọc Khánh, Hà Nội",
        "ngheNghiep": "Thợ xây",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "22/06/2023",
        "ngayKetThuc": "06/08/2023",
        "lyDo": "Điều trị y tế chuyên sâu.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 27,
        "hoTen": "Vũ/Võ Linh Chi",
        "gioiTinh": "Nữ",
        "ngaySinh": "24/03/1985",
        "SDT": "0703667116",
        "CCCD": "008176495705",
        "DDThuongTru": "Vạn Phúc, Hà Đông, Hà Nội",
        "ngheNghiep": "Thợ hàn",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "26/01/2023",
        "ngayKetThuc": "12/03/2023",
        "lyDo": "Tìm kiếm cơ hội việc làm.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 28,
        "hoTen": "Bùi Hồng Quân",
        "gioiTinh": "Nam",
        "ngaySinh": "21/11/1983",
        "SDT": "0649189747",
        "CCCD": "024224525295",
        "DDThuongTru": "Xuân La, Hà Nội",
        "ngheNghiep": "Đầu bếp",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "05/03/2023",
        "ngayKetThuc": "20/04/2023",
        "lyDo": "Nghỉ dưỡng sau phẫu thuật.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 29,
        "hoTen": "Giang Uyển Nhi",
        "gioiTinh": "Nữ",
        "ngaySinh": "31/08/1987",
        "SDT": "0593680689",
        "CCCD": "095271877718",
        "DDThuongTru": "Cổ Bi, Hà Nội",
        "ngheNghiep": "Phục vụ nhà hàng",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "28/06/2023",
        "ngayKetThuc": "28/07/2023",
        "lyDo": "Hợp tác quốc tế.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 30,
        "hoTen": "Vũ/Võ Yến Nhi",
        "gioiTinh": "Nữ",
        "ngaySinh": "31/01/1980",
        "SDT": "0521722785",
        "CCCD": "076180596472",
        "DDThuongTru": "Phú La, Hà Nội",
        "ngheNghiep": "Lao động phổ thông",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "27/12/2023",
        "ngayKetThuc": "23/1/2024",
        "lyDo": "Tham gia khóa học ngắn hạn.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 31,
        "hoTen": "Tô Ý Nhiên",
        "gioiTinh": "Nữ",
        "ngaySinh": "12/05/1987",
        "SDT": "0633466920",
        "CCCD": "008282569293",
        "DDThuongTru": "Tả Thanh Oai, Thanh Trì, Hà Nội",
        "ngheNghiep": "Nhân viên văn phòng",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "10/01/2023",
        "ngayKetThuc": "08/02/2023",
        "lyDo": "Thực hiện công tác từ thiện.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 32,
        "hoTen": "Nguyễn Xuân Mai",
        "gioiTinh": "Nữ",
        "ngaySinh": "28/01/2004",
        "SDT": "0715056315",
        "CCCD": "006157562234",
        "DDThuongTru": "Kim Lũ, Hà Nội",
        "ngheNghiep": "Nhân viên bán hàng",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "25/04/2023",
        "ngayKetThuc": "27/05/2023",
        "lyDo": "Tạm trú sau thiên tai.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 33,
        "hoTen": "Hà Quỳnh Như",
        "gioiTinh": "Nữ",
        "ngaySinh": "22/12/1992",
        "SDT": "0407737330",
        "CCCD": "083106032714",
        "DDThuongTru": "Vân Canh, Hoài Đức, Hà Nội",
        "ngheNghiep": "Nhân viên ngân hàng",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "28/11/2023",
        "ngayKetThuc": "1/1/2024",
        "lyDo": "Làm việc tại đại sứ quán.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 34,
        "hoTen": "Huỳnh/Hoàng Chi Mai",
        "gioiTinh": "Nữ",
        "ngaySinh": "19/02/2005",
        "SDT": "0166838801",
        "CCCD": "054262430167",
        "DDThuongTru": "Hòa Lạc, Hà Nội",
        "ngheNghiep": "Tài xế xe tải",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "06/06/2023",
        "ngayKetThuc": "05/07/2023",
        "lyDo": "Điều tra thị trường mới.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 35,
        "hoTen": "Nguyễn Thúy Vân",
        "gioiTinh": "Nữ",
        "ngaySinh": "17/04/1980",
        "SDT": "0764544429",
        "CCCD": "016152205649",
        "DDThuongTru": "Minh Châu, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Tài xế taxi",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "30/11/2023",
        "ngayKetThuc": "12/12/2023",
        "lyDo": "Nghệ sĩ thực hiện dự án.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 36,
        "hoTen": "Hàn Thúy Vân",
        "gioiTinh": "Nữ",
        "ngaySinh": "19/03/1998",
        "SDT": "0347236016",
        "CCCD": "072238420674",
        "DDThuongTru": "Bắc Hồng, Gia Lâm, Hà Nội",
        "ngheNghiep": "Lái xe buýt",
        "DDTamTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngayBatDau": "13/04/2023",
        "ngayKetThuc": "29/04/2023",
        "lyDo": "Tham dự hội nghị quốc tế.",
        "canHo": "s1",
        "trangThai": "0"
    }
]
var tableDonTamVang =[
    {
        "id": 1,
        "hoTen": "Vũ Văn Trang",
        "gioiTinh": "Nam",
        "ngaySinh": "02/12/1993",
        "SDT": "0103832654",
        "CCCD": "084239031603",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Giáo viên",
        "DDTamVang": "Xã Tây Bắc, Huyện Long Biên, Hải Phòng",
        "ngayBatDau": "02/03/2023",
        "ngayKetThuc": "18/04/2023",
        "lyDo": "Đi nghỉ mát hoặc du lịch.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 2,
        "hoTen": "Lê Công Minh",
        "gioiTinh": "Nữ",
        "ngaySinh": "26/08/1989",
        "SDT": "0438771365",
        "CCCD": "003198212513",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Bác sĩ",
        "DDTamVang": "Xã Tây Bắc, Huyện Tây Hồ, Hải Phòng",
        "ngayBatDau": "03/05/2023",
        "ngayKetThuc": "08/06/2023",
        "lyDo": "Công tác.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 3,
        "hoTen": "Phan Thành Dương",
        "gioiTinh": "Nữ",
        "ngaySinh": "26/03/1984",
        "SDT": "0355817526",
        "CCCD": "049156119984",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Y tá",
        "DDTamVang": "Xã Minh Đức, Huyện Tây Hồ, Cần Thơ",
        "ngayBatDau": "03/06/2023",
        "ngayKetThuc": "13/06/2023",
        "lyDo": "Thăm bè bạn hoặc người thân.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 4,
        "hoTen": "Lê Đức Bình",
        "gioiTinh": "Nữ",
        "ngaySinh": "25/04/1993",
        "SDT": "0449948650",
        "CCCD": "049106868261",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Kỹ sư",
        "DDTamVang": "Xã Tây Bắc, Huyện Đống Đa, Bình Dương",
        "ngayBatDau": "03/06/2023",
        "ngayKetThuc": "18/07/2023",
        "lyDo": "Điều trị y tế hoặc nằm viện.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 5,
        "hoTen": "Vũ Hữu Minh",
        "gioiTinh": "Nam",
        "ngaySinh": "04/11/1990",
        "SDT": "0458037641",
        "CCCD": "002283103668",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Lập trình viên",
        "DDTamVang": "Xã Thượng Đức, Huyện Ba Đình, Hải Dương",
        "ngayBatDau": "03/10/2023",
        "ngayKetThuc": "05/10/2023",
        "lyDo": "Tham dự đám cưới hoặc sự kiện gia đình.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 6,
        "hoTen": "Nguyễn Thành Bình",
        "gioiTinh": "Nam",
        "ngaySinh": "26/05/1986",
        "SDT": "0800329919",
        "CCCD": "084216304265",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Kiến trúc sư",
        "DDTamVang": "Xã Đại Phú, Huyện Sóc Sơn, Hải Dương",
        "ngayBatDau": "03/12/2023",
        "ngayKetThuc": "18/01/2024",
        "lyDo": "Theo đuổi mục tiêu giáo dục, như học kỳ ở nước ngoài.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 7,
        "hoTen": "Võ Đức Bình",
        "gioiTinh": "Nam",
        "ngaySinh": "09/05/1987",
        "SDT": "0235481724",
        "CCCD": "060168453203",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ xây",
        "DDTamVang": "Xã Phú Lâm, Huyện Hai Bà Trưng, Bình Dương",
        "ngayBatDau": "04/04/2023",
        "ngayKetThuc": "17/04/2023",
        "lyDo": "Công việc ở thành phố hoặc quốc gia khác.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 8,
        "hoTen": "Hoàng Văn Kiên",
        "gioiTinh": "Nam",
        "ngaySinh": "10/12/1998",
        "SDT": "0729954186",
        "CCCD": "093184197259",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ hàn",
        "DDTamVang": "Xã Đông Hải, Huyện Ba Đình, Hà Nội",
        "ngayBatDau": "04/11/2023",
        "ngayKetThuc": "10/11/2023",
        "lyDo": "Tham dự hội nghị hoặc phát triển chuyên nghiệp.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 9,
        "hoTen": "Phan Thị Nam",
        "gioiTinh": "Nữ",
        "ngaySinh": "19/12/1999",
        "SDT": "0186735551",
        "CCCD": "058212880352",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Đầu bếp",
        "DDTamVang": "Xã Bắc Phú, Huyện Hai Bà Trưng, Đà Nẵng",
        "ngayBatDau": "05/02/2023",
        "ngayKetThuc": "10/03/2023",
        "lyDo": "Tham gia chương trình tình nguyện.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 10,
        "hoTen": "Hoàng Thành Minh",
        "gioiTinh": "Nữ",
        "ngaySinh": "31/03/1998",
        "SDT": "0497041759",
        "CCCD": "072162776417",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Phục vụ nhà hàng",
        "DDTamVang": "Xã Đại Phú, Huyện Tây Hồ, Gia Lai",
        "ngayBatDau": "05/09/2023",
        "ngayKetThuc": "17/10/2023",
        "lyDo": "Nghĩa vụ quân sự.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 11,
        "hoTen": "Huỳnh Đức Hải",
        "gioiTinh": "Nam",
        "ngaySinh": "19/03/2002",
        "SDT": "0914189079",
        "CCCD": "053183436818",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Lao động phổ thông",
        "DDTamVang": "Xã Đại Phú, Huyện Hai Châu, Hải Phòng",
        "ngayBatDau": "05/10/2023",
        "ngayKetThuc": "27/10/2023",
        "lyDo": "Nghĩa vụ bồi thẩm đoàn.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 12,
        "hoTen": "Lê Thành Nam",
        "gioiTinh": "Nam",
        "ngaySinh": "08/11/1997",
        "SDT": "0706960594",
        "CCCD": "077111314571",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên văn phòng",
        "DDTamVang": "Xã Nam Sơn, Huyện Tây Hồ, Nghệ An",
        "ngayBatDau": "06/02/2023",
        "ngayKetThuc": "01/03/2023",
        "lyDo": "Nghỉ phép nghiên cứu.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 13,
        "hoTen": "Huỳnh Minh Anh",
        "gioiTinh": "Nữ",
        "ngaySinh": "12/08/1993",
        "SDT": "0269840364",
        "CCCD": "091168730956",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên bán hàng",
        "DDTamVang": "Xã Đại Phú, Huyện Ba Đình, Bình Dương",
        "ngayBatDau": "07/12/2023",
        "ngayKetThuc": "30/12/2023",
        "lyDo": "Chuyến đi nghiên cứu học thuật hoặc khoa học.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 14,
        "hoTen": "Vũ Đức Minh",
        "gioiTinh": "Nam",
        "ngaySinh": "07/02/1989",
        "SDT": "0491379892",
        "CCCD": "075205809671",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên ngân hàng",
        "DDTamVang": "Xã Minh Đức, Huyện Sóc Sơn, Đà Nẵng",
        "ngayBatDau": "08/05/2023",
        "ngayKetThuc": "26/05/2023",
        "lyDo": "Thực tập hoặc học bổng.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 15,
        "hoTen": "Lê Thị Linh",
        "gioiTinh": "Nam",
        "ngaySinh": "01/12/1989",
        "SDT": "0509700946",
        "CCCD": "030219219497",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Tài xế xe tải",
        "DDTamVang": "Xã Đại Phú, Huyện Hoàn Kiếm, Gia Lai",
        "ngayBatDau": "08/06/2023",
        "ngayKetThuc": "13/07/2023",
        "lyDo": "Du lịch phiêu lưu hoặc khám phá.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 16,
        "hoTen": "Phan Quang Trang",
        "gioiTinh": "Nam",
        "ngaySinh": "19/02/2003",
        "SDT": "0344446991",
        "CCCD": "044159438526",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Tài xế taxi",
        "DDTamVang": "Xã Trung Hưng, Huyện Hoàn Kiếm, Bình Dương",
        "ngayBatDau": "08/07/2023",
        "ngayKetThuc": "20/08/2023",
        "lyDo": "Hành hương tôn giáo hoặc tu tập tâm linh.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 17,
        "hoTen": "Hoàng Đức Kiên",
        "gioiTinh": "Nam",
        "ngaySinh": "07/12/1999",
        "SDT": "0424639572",
        "CCCD": "048259781309",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Lái xe buýt",
        "DDTamVang": "Xã Đại Phú, Huyện Ba Đình, Cần Thơ",
        "ngayBatDau": "09/06/2023",
        "ngayKetThuc": "15/06/2023",
        "lyDo": "Chăm sóc người thân ốm đau.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 18,
        "hoTen": "Hoàng Minh Hải",
        "gioiTinh": "Nữ",
        "ngaySinh": "19/08/1999",
        "SDT": "0151528880",
        "CCCD": "069294614855",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Cảnh sát",
        "DDTamVang": "Xã Phú Lâm, Huyện Long Biên, TP Hồ Chí Minh",
        "ngayBatDau": "09/10/2023",
        "ngayKetThuc": "03/11/2023",
        "lyDo": "Nghỉ tang do tử vong trong gia đình.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 19,
        "hoTen": "Nguyễn Minh Hải",
        "gioiTinh": "Nam",
        "ngaySinh": "31/05/1994",
        "SDT": "0514900359",
        "CCCD": "003157030244",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Lính cứu hỏa",
        "DDTamVang": "Xã Phú Lâm, Huyện Hai Bà Trưng, Nghệ An",
        "ngayBatDau": "09/12/2023",
        "ngayKetThuc": "25/12/2023",
        "lyDo": "Nghỉ thai sản hoặc nuôi con nhỏ.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 20,
        "hoTen": "Phạm Ngọc Kiên",
        "gioiTinh": "Nữ",
        "ngaySinh": "29/10/1981",
        "SDT": "0244887596",
        "CCCD": "083118733673",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhiếp ảnh gia",
        "DDTamVang": "Xã Bắc Phú, Huyện Hoàn Kiếm, Thanh Hóa",
        "ngayBatDau": "13/01/2023",
        "ngayKetThuc": "19/02/2023",
        "lyDo": "Sửa chữa hoặc tu sửa nhà cần di dời tạm thời.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 21,
        "hoTen": "Phan Đức Trang",
        "gioiTinh": "Nam",
        "ngaySinh": "04/05/1983",
        "SDT": "0453501477",
        "CCCD": "026182074079",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhà báo",
        "DDTamVang": "Xã Hòa Minh, Huyện Đống Đa, Thanh Hóa",
        "ngayBatDau": "14/05/2023",
        "ngayKetThuc": "30/06/2023",
        "lyDo": "Sơ tán do thảm họa tự nhiên như lũ lụt hoặc bão.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 22,
        "hoTen": "Phạm Bảo Kiên",
        "gioiTinh": "Nam",
        "ngaySinh": "13/12/2005",
        "SDT": "0310021654",
        "CCCD": "089206934056",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Biên tập viên",
        "DDTamVang": "Xã Bắc Phú, Huyện Hai Châu, Hải Dương",
        "ngayBatDau": "14/10/2023",
        "ngayKetThuc": "09/11/2023",
        "lyDo": "Việc pháp lý hoặc xuất hiện tại tòa ở địa điểm khác.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 23,
        "hoTen": "Vũ Đức Nam",
        "gioiTinh": "Nữ",
        "ngaySinh": "02/04/2003",
        "SDT": "0533326705",
        "CCCD": "008205676602",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Đạo diễn",
        "DDTamVang": "Xã Nam Sơn, Huyện Hai Bà Trưng, Nghệ An",
        "ngayBatDau": "15/05/2023",
        "ngayKetThuc": "09/06/2023",
        "lyDo": "Du lịch mùa lễ hội dài ngày.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 24,
        "hoTen": "Vũ Thị Nam",
        "gioiTinh": "Nam",
        "ngaySinh": "10/12/2002",
        "SDT": "0768272756",
        "CCCD": "087275462300",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Diễn viên",
        "DDTamVang": "Xã Đại Phú, Huyện Hai Bà Trưng, Đà Nẵng",
        "ngayBatDau": "16/05/2023",
        "ngayKetThuc": "27/06/2023",
        "lyDo": "Tham gia giải đấu thể thao hoặc sự kiện.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 25,
        "hoTen": "Huỳnh Thị Linh",
        "gioiTinh": "Nam",
        "ngaySinh": "29/10/1997",
        "SDT": "0271095344",
        "CCCD": "017199029863",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Ca sĩ",
        "DDTamVang": "Xã Hòa Minh, Huyện Cầu Giấy, Hải Dương",
        "ngayBatDau": "16/08/2023",
        "ngayKetThuc": "02/09/2023",
        "lyDo": "Tham gia vào hoạt động văn hóa hoặc nghệ thuật.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 26,
        "hoTen": "Vũ Thành Linh",
        "gioiTinh": "Nữ",
        "ngaySinh": "25/02/1998",
        "SDT": "0824207215",
        "CCCD": "005220467526",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhạc sĩ",
        "DDTamVang": "Xã Phú Lâm, Huyện Đống Đa, Hà Nội",
        "ngayBatDau": "17/02/2023",
        "ngayKetThuc": "21/03/2023",
        "lyDo": "Tham dự trại hè hoặc tu tập.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 27,
        "hoTen": "Phan Minh Kiên",
        "gioiTinh": "Nam",
        "ngaySinh": "25/07/1991",
        "SDT": "0494725198",
        "CCCD": "025257593628",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Họa sĩ",
        "DDTamVang": "Xã Phú Lâm, Huyện Ba Đình, TP Hồ Chí Minh",
        "ngayBatDau": "18/04/2023",
        "ngayKetThuc": "01/05/2023",
        "lyDo": "Tu dưỡng sức khỏe và tinh thần.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 28,
        "hoTen": "Phạm Bảo Anh",
        "gioiTinh": "Nam",
        "ngaySinh": "14/02/2002",
        "SDT": "0390328828",
        "CCCD": "071140311737",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhà thiết kế thời trang",
        "DDTamVang": "Xã Nam Sơn, Huyện Hai Bà Trưng, Thanh Hóa",
        "ngayBatDau": "18/06/2023",
        "ngayKetThuc": "23/06/2023",
        "lyDo": "Nghỉ phép cá nhân cho sự nghỉ ngơi và phục hồi.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 29,
        "hoTen": "Vũ Ngọc Chi",
        "gioiTinh": "Nam",
        "ngaySinh": "25/11/1981",
        "SDT": "0529145029",
        "CCCD": "073232709058",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ may",
        "DDTamVang": "Xã Đại Phú, Huyện Hai Châu, Hải Phòng",
        "ngayBatDau": "19/03/2023",
        "ngayKetThuc": "28/03/2023",
        "lyDo": "Theo đuổi sở thích hoặc mục tiêu một cách chuyên sâu, như chuyến đi chụp ảnh.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 30,
        "hoTen": "Phan Đức Chi",
        "gioiTinh": "Nam",
        "ngaySinh": "21/09/1981",
        "SDT": "0263528342",
        "CCCD": "049262726379",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ làm tóc",
        "DDTamVang": "Xã Đông Hải, Huyện Ba Đình, Đà Nẵng",
        "ngayBatDau": "19/07/2023",
        "ngayKetThuc": "16/08/2023",
        "lyDo": "Đào bới khảo cổ hoặc nghiên cứu lịch sử.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 31,
        "hoTen": "Phạm Quang Chi",
        "gioiTinh": "Nam",
        "ngaySinh": "19/05/1996",
        "SDT": "0818680789",
        "CCCD": "064174943659",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Chuyên viên làm đẹp",
        "DDTamVang": "Xã Bắc Phú, Huyện Ba Đình, Hải Dương",
        "ngayBatDau": "20/01/2023",
        "ngayKetThuc": "14/02/2023",
        "lyDo": "Làm việc mùa vụ ở khu vực khác.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 32,
        "hoTen": "Hoàng Công Bình",
        "gioiTinh": "Nam",
        "ngaySinh": "03/08/1994",
        "SDT": "0405542541",
        "CCCD": "026268397434",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thợ sửa chữa điện tử",
        "DDTamVang": "Xã Đông Hải, Huyện Cầu Giấy, Thanh Hóa",
        "ngayBatDau": "21/01/2023",
        "ngayKetThuc": "24/02/2023",
        "lyDo": "Chuyến đi săn hoặc câu cá kéo dài.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 33,
        "hoTen": "Đặng Văn Linh",
        "gioiTinh": "Nam",
        "ngaySinh": "29/09/1989",
        "SDT": "0245115767",
        "CCCD": "080105374516",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Kỹ thuật viên máy tính",
        "DDTamVang": "Xã Phú Lâm, Huyện Hai Châu, Hà Nội",
        "ngayBatDau": "21/04/2023",
        "ngayKetThuc": "23/05/2023",
        "lyDo": "Hoạt động chính trị hoặc vận động.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 34,
        "hoTen": "Lê Thành Bình",
        "gioiTinh": "Nữ",
        "ngaySinh": "28/05/1987",
        "SDT": "0378372826",
        "CCCD": "068260811059",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên tiếp thị",
        "DDTamVang": "Xã Thượng Đức, Huyện Đống Đa, Hải Dương",
        "ngayBatDau": "21/09/2023",
        "ngayKetThuc": "02/11/2023",
        "lyDo": "Tham gia chương trình cai nghiện hoặc phục hồi sức khỏe.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 35,
        "hoTen": "Phan Thành Nam",
        "gioiTinh": "Nữ",
        "ngaySinh": "29/05/1998",
        "SDT": "0571847246",
        "CCCD": "068260266856",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Chuyên gia SEO",
        "DDTamVang": "Xã Trung Hưng, Huyện Hai Châu, Cần Thơ",
        "ngayBatDau": "21/10/2023",
        "ngayKetThuc": "26/11/2023",
        "lyDo": "Tham gia chương trình truyền hình thực tế hoặc cuộc thi.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 36,
        "hoTen": "Đặng Văn Trang",
        "gioiTinh": "Nữ",
        "ngaySinh": "19/06/1987",
        "SDT": "0461443112",
        "CCCD": "052225441829",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhà phân tích dữ liệu",
        "DDTamVang": "Xã Đại Phú, Huyện Tây Hồ, Hải Phòng",
        "ngayBatDau": "22/04/2023",
        "ngayKetThuc": "03/06/2023",
        "lyDo": "Tham gia sự kiện từ thiện đường dài như marathon.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 37,
        "hoTen": "Huỳnh Ngọc Bình",
        "gioiTinh": "Nam",
        "ngaySinh": "30/01/2002",
        "SDT": "0132737326",
        "CCCD": "044201854972",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Chuyên gia tư vấn",
        "DDTamVang": "Xã Đông Hải, Huyện Hoàn Kiếm, Thanh Hóa",
        "ngayBatDau": "22/05/2023",
        "ngayKetThuc": "11/07/2023",
        "lyDo": "Học và thi cử kéo dài.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 38,
        "hoTen": "Đặng Bảo Minh",
        "gioiTinh": "Nữ",
        "ngaySinh": "13/05/2001",
        "SDT": "0463172124",
        "CCCD": "009286615595",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Luật sư",
        "DDTamVang": "Xã Thượng Đức, Huyện Cầu Giấy, Cần Thơ",
        "ngayBatDau": "24/05/2023",
        "ngayKetThuc": "11/07/2023",
        "lyDo": "Di dời tạm thời do bất ổn hoặc nguy hiểm trong khu vực.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 39,
        "hoTen": "Phạm Thành Nam",
        "gioiTinh": "Nữ",
        "ngaySinh": "09/01/1985",
        "SDT": "0794848708",
        "CCCD": "073258182525",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Kế toán",
        "DDTamVang": "Xã Tây Bắc, Huyện Tây Hồ, Nghệ An",
        "ngayBatDau": "24/07/2023",
        "ngayKetThuc": "08/08/2023",
        "lyDo": "Hoạt động thể thao chuyên nghiệp.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 40,
        "hoTen": "Huỳnh Văn Nam",
        "gioiTinh": "Nữ",
        "ngaySinh": "29/07/1984",
        "SDT": "0370067901",
        "CCCD": "023254628993",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Thủ quỹ",
        "DDTamVang": "Xã Đông Hải, Huyện Liên Chiểu, Hà Nội",
        "ngayBatDau": "24/09/2023",
        "ngayKetThuc": "10/10/2023",
        "lyDo": "Thực hiện hành trình thực hiện danh sách mong muốn cá nhân.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 41,
        "hoTen": "Nguyễn Văn Chi",
        "gioiTinh": "Nam",
        "ngaySinh": "13/05/1984",
        "SDT": "0926896031",
        "CCCD": "087174209267",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Quản lý khách sạn",
        "DDTamVang": "Xã Đại Phú, Huyện Cầu Giấy, Gia Lai",
        "ngayBatDau": "24/11/2023",
        "ngayKetThuc": "15/12/2023",
        "lyDo": "Nghỉ để viết sách hoặc theo đuổi dự án sáng tạo.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 42,
        "hoTen": "Vũ Văn Trang",
        "gioiTinh": "Nữ",
        "ngaySinh": "25/09/1980",
        "SDT": "0512456814",
        "CCCD": "080207957640",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên lễ tân",
        "DDTamVang": "Xã Minh Đức, Huyện Sóc Sơn, Đà Nẵng",
        "ngayBatDau": "25/07/2023",
        "ngayKetThuc": "07/08/2023",
        "lyDo": "Tham dự hàng loạt lễ hội hoặc buổi hòa nhạc.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 43,
        "hoTen": "Hoàng Quang Nam",
        "gioiTinh": "Nam",
        "ngaySinh": "20/08/1981",
        "SDT": "0558622486",
        "CCCD": "091242641222",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Hướng dẫn viên du lịch",
        "DDTamVang": "Xã Bắc Phú, Huyện Hai Bà Trưng, Đà Nẵng",
        "ngayBatDau": "26/11/2023",
        "ngayKetThuc": "12/12/2023",
        "lyDo": "Theo dõi đoàn kịch hoặc nhóm nhạc lưu diễn.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 44,
        "hoTen": "Phan Ngọc Chi",
        "gioiTinh": "Nam",
        "ngaySinh": "22/03/1997",
        "SDT": "0180135416",
        "CCCD": "007178635049",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Phi công",
        "DDTamVang": "Xã Đại Phú, Huyện Tây Hồ, Gia Lai",
        "ngayBatDau": "27/02/2023",
        "ngayKetThuc": "24/03/2023",
        "lyDo": "Phục vụ như một nhà ngoại giao hoặc tư vấn.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 45,
        "hoTen": "Huỳnh Đức Linh",
        "gioiTinh": "Nữ",
        "ngaySinh": "22/02/1985",
        "SDT": "0593182031",
        "CCCD": "089174191337",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Tiếp viên hàng không",
        "DDTamVang": "Xã Nam Sơn, Huyện Tây Hồ, Nghệ An",
        "ngayBatDau": "27/11/2023",
        "ngayKetThuc": "10/01/2024",
        "lyDo": "Tham gia chương trình huấn luyện sinh tồn.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 46,
        "hoTen": "Phan Thành Dương",
        "gioiTinh": "Nam",
        "ngaySinh": "10/06/1985",
        "SDT": "0182737885",
        "CCCD": "047109134283",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên an ninh sân bay",
        "DDTamVang": "Xã Phú Lâm, Huyện Ba Đình, TP Hồ Chí Minh",
        "ngayBatDau": "28/09/2023",
        "ngayKetThuc": "17/10/2023",
        "lyDo": "Tiến hành nghiên cứu thực địa về môi trường.",
        "canHo": "s2",
        "trangThai": "0"
    },
    {
        "id": 47,
        "hoTen": "Nguyễn Quang Kiên",
        "gioiTinh": "Nữ",
        "ngaySinh": "06/05/2000",
        "SDT": "0746788046",
        "CCCD": "057234227648",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhân viên kiểm tra hành lý",
        "DDTamVang": "Xã Đại Phú, Huyện Ba Đình, Bình Dương",
        "ngayBatDau": "28/10/2023",
        "ngayKetThuc": "15/11/2023",
        "lyDo": "Phẫu thuật thẩm mỹ hoặc tự chọn.",
        "canHo": "s1",
        "trangThai": "0"
    },
    {
        "id": 48,
        "hoTen": "Vũ Hữu Linh",
        "gioiTinh": "Nữ",
        "ngaySinh": "12/07/1993",
        "SDT": "0809171542",
        "CCCD": "041211334390",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Nhà nghiên cứu khoa học",
        "DDTamVang": "Xã Minh Đức, Huyện Sóc Sơn, Đà Nẵng",
        "ngayBatDau": "29/01/2023",
        "ngayKetThuc": "26/02/2023",
        "lyDo": "Tham gia sứ mệnh ngoại giao hoặc chương trình trao đổi.",
        "canHo": "s1",
        "trangThai": "1"
    },
    {
        "id": 49,
        "hoTen": "Lê Quang Minh",
        "gioiTinh": "Nữ",
        "ngaySinh": "16/12/1992",
        "SDT": "0613256529",
        "CCCD": "094224015995",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Giáo sư đại học",
        "DDTamVang": "Xã Đại Phú, Huyện Hoàn Kiếm, Gia Lai",
        "ngayBatDau": "29/06/2023",
        "ngayKetThuc": "15/07/2023",
        "lyDo": "Tham gia tái hiện lịch sử hoặc lễ hội.",
        "canHo": "s2",
        "trangThai": "1"
    },
    {
        "id": 50,
        "hoTen": "Trần Bảo Nam",
        "gioiTinh": "Nữ",
        "ngaySinh": "30/07/1980",
        "SDT": "0915368255",
        "CCCD": "023145403650",
        "DDThuongTru": "Bắc Phú, Sóc Sơn, Hà Nội",
        "ngheNghiep": "Sinh viên",
        "DDTamVang": "Xã Minh Đức, Huyện Sóc Sơn, Đà Nẵng",
        "ngayBatDau": "29/10/2023",
        "ngayKetThuc": "29/11/2023",
        "lyDo": "Tham dự sự kiện công việc của đối tác.",
        "canHo": "s1",
        "trangThai": "0"
    }
]




/*
	1 - Loop Through Array & Access each value
  2 - Create Table Rows & append to table
*/


// Khởi tạo và Tải dữ liệu từ localStorage
function loadtableDonTamTruFromLocalStorage() {
    var storedData = localStorage.getItem('tableDonTamTru');
    if (storedData) {
        tableDonTamTru = JSON.parse(storedData);
    }
}
// Khởi tạo và Tải dữ liệu từ localStorage
function loadtableDonTamVangFromLocalStorage() {
    var storedData = localStorage.getItem('tableDonTamVang');
    if (storedData) {
        tableDonTamVang = JSON.parse(storedData);
    }
}
loadtableDonTamVangFromLocalStorage();
loadtableDonTamTruFromLocalStorage();